//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiFlight.ProjectMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectMessages_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectMessages_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobiFlight.ProjectMessages.ProjectMessages.de", typeof(ProjectMessages_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Adresse eines Display Moduls darf nicht null sein. Bitte prüfen Sie Ihre Konfigurationsdatei..
        /// </summary>
        internal static string ConfigErrorException_AddressNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_AddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seriennummer eines Moduls darf nicht null sein. Bitte prüfen Sie Ihre Konfigurationsdatei..
        /// </summary>
        internal static string ConfigErrorException_SerialNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_SerialNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Schreiben von Werten auf das Display Modul. Bitte prüfen Sie Ihre Konfigurationsdatei..
        /// </summary>
        internal static string ConfigErrorException_WritingDisplay {
            get {
                return ResourceManager.GetString("ConfigErrorException_WritingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinden.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neu.
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trennen.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der untere Wert für den Sim-Bereich muss kleiner als der obere Wert für den Sim-Bereich sein..
        /// </summary>
        internal static string DisplayPWMPinPanel_SetTrackBar_Sim_lower_less_than_sim_upper_ {
            get {
                return ResourceManager.GetString("DisplayPWMPinPanel_SetTrackBar_Sim_lower_less_than_sim_upper_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSUIPC Status.
        /// </summary>
        internal static string fsuipcStatus {
            get {
                return ResourceManager.GetString("fsuipcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabeprüfung.
        /// </summary>
        internal static string InputValidation {
            get {
                return ResourceManager.GetString("InputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string LabelPrecondition_ArcazePin {
            get {
                return ResourceManager.GetString("LabelPrecondition_ArcazePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Eintrag.
        /// </summary>
        internal static string LabelPrecondition_ConfigItem {
            get {
                return ResourceManager.GetString("LabelPrecondition_ConfigItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine.
        /// </summary>
        internal static string LabelPrecondition_None {
            get {
                return ResourceManager.GetString("LabelPrecondition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden Änderungen an der Konfiguration von MobiFlight Modulen gemacht und diese Änderungen wurden noch nicht auf die Module gespeichert. Möchtest Du trotzdem den Dialog schließen? Die Änderungen gehen dabei verloren..
        /// </summary>
        internal static string MFModuleConfigChanged {
            get {
                return ResourceManager.GetString("MFModuleConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keins.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen.
        /// </summary>
        internal static string Please_Choose {
            get {
                return ResourceManager.GetString("Please_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie einen Pin..
        /// </summary>
        internal static string Please_select_a_pin {
            get {
                return ResourceManager.GetString("Please_select_a_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie einen Port..
        /// </summary>
        internal static string Please_select_a_port {
            get {
                return ResourceManager.GetString("Please_select_a_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läuft.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSUIPC ist verbunden..
        /// </summary>
        internal static string statusFsuipcConnected {
            get {
                return ResourceManager.GetString("statusFsuipcConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestoppt.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie.
        /// </summary>
        internal static string suffixCopy {
            get {
                return ResourceManager.GetString("suffixCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Modus.
        /// </summary>
        internal static string TestMode {
            get {
                return ResourceManager.GetString("TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führe zeilenweise Konfiguration aus und steuere jede Ausgabe für einen Test an.
        /// </summary>
        internal static string TestModeToolTip {
            get {
                return ResourceManager.GetString("TestModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config object ist null..
        /// </summary>
        internal static string uiException_ConfigItemNotFound {
            get {
                return ResourceManager.GetString("uiException_ConfigItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} braucht Pin {1} welcher bereits verwendet wird. Lösche die Zuordnung und versuche es mit {0} nochmal..
        /// </summary>
        internal static string uiI2CPinInUse {
            get {
                return ResourceManager.GetString("uiI2CPinInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I2C Pin in Verwendung.
        /// </summary>
        internal static string uiI2CPinInUseHint {
            get {
                return ResourceManager.GetString("uiI2CPinInUseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppelklicken für neuen Eintrag....
        /// </summary>
        internal static string uiLabelDoubleClickToAddConfig {
            get {
                return ResourceManager.GetString("uiLabelDoubleClickToAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anwendung läuft jetzt im Hintergrund..
        /// </summary>
        internal static string uiMessageApplicationIsRunningInBackgroundMode {
            get {
                return ResourceManager.GetString("uiMessageApplicationIsRunningInBackgroundMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Arcaze Modul wurde entfernt..
        /// </summary>
        internal static string uiMessageAraceUSBHasBeenRemoved {
            get {
                return ResourceManager.GetString("uiMessageAraceUSBHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung mit einem Arcaze Modul wurde unterbrochen..
        /// </summary>
        internal static string uiMessageArcazeConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageArcazeConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die als Parameter übergebene Config-Datei existiert nicht..
        /// </summary>
        internal static string uiMessageCmdParamConfigFileDoesNotExist {
            get {
                return ResourceManager.GetString("uiMessageCmdParamConfigFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Zeile wurde noch nicht gespeichert und kann daher nicht bearbeitet werden.
        ///Legen Sie zuerst den Beschreibungstext fest und editieren Sie dann den Eintrag..
        /// </summary>
        internal static string uiMessageConfigLineNotSavedYet {
            get {
                return ResourceManager.GetString("uiMessageConfigLineNotSavedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration konnte nicht geladen werden. Check den Pfad zur Datei..
        /// </summary>
        internal static string uiMessageConfigNotFound {
            get {
                return ResourceManager.GetString("uiMessageConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Presets. Presets können nicht aus der Liste gewählt werden..
        /// </summary>
        internal static string uiMessageConfigWizard_ErrorLoadingPresets {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ErrorLoadingPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei mit Presets konnte nicht im aktuellen Verzeichnis gefunden werden..
        /// </summary>
        internal static string uiMessageConfigWizard_PresetsNotFound {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_PresetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die gewünschte Adresse des Display Driver an. Es muss numerisch sein, z.B. 1..
        /// </summary>
        internal static string uiMessageConfigWizard_ProvideLedDisplayAddress {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ProvideLedDisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gültiges Modul aus Liste auswählen..
        /// </summary>
        internal static string uiMessageConfigWizard_SelectArcaze {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectArcaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie eine Art für den Vergleich an..
        /// </summary>
        internal static string uiMessageConfigWizard_SelectComparison {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown precondition type from config.
        /// </summary>
        internal static string uiMessageConfigWizard_UnknownPreconditionType {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_UnknownPreconditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte prüfen Sie die Angabe und geben Sie ein gültiges Hex-Format an (0x0-0xF)..
        /// </summary>
        internal static string uiMessageConfigWizard_ValidHexFormat {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ValidHexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind nur Zahlen erlaubt. Bitte prüfe Deine Eingabe..
        /// </summary>
        internal static string uiMessageConfigWizardInterpolationOnlyNumbersPlease {
            get {
                return ResourceManager.GetString("uiMessageConfigWizardInterpolationOnlyNumbersPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind noch Änderungen ungespeichert.
        ///Möchten Sie die Änderungen jetzt speichern?.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsaved {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte prüfen Sie.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsavedTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie wirkliche eine neue Konfiguration anlegen?
        ///Alle ungespeicherten Änderungen gehen dabei verloren..
        /// </summary>
        internal static string uiMessageConfirmNewConfig {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätigen Sie.
        /// </summary>
        internal static string uiMessageConfirmNewConfigTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name ist für ein angeschlossenes Gerät schon verwendet. Gerätenamen müssen eindeutig sein. Bitte prüfen..
        /// </summary>
        internal static string uiMessageDeviceNameAlreadyUsed {
            get {
                return ResourceManager.GetString("uiMessageDeviceNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Name oder zu lang (max. {1} Zeichen). Die folgenden Buchstaben können nicht verwendet werden:
        ///{0}.
        /// </summary>
        internal static string uiMessageDeviceNameContainsInvalidCharsOrTooLong {
            get {
                return ResourceManager.GetString("uiMessageDeviceNameContainsInvalidCharsOrTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Anwendung Ihrer Formel trat ein Fehler auf. Bitte prüfen Sie Ihre Formel..
        /// </summary>
        internal static string uiMessageErrorOnParsingExpression {
            get {
                return ResourceManager.GetString("uiMessageErrorOnParsingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte prüfe Deine Firmware-Flash-Einstellungen.
        ///Du musst einen gültigen Pfad zu Deiner Arduino IDE angeben (min. 1.0.5)..
        /// </summary>
        internal static string uiMessageFirmwareCheckPath {
            get {
                return ResourceManager.GetString("uiMessageFirmwareCheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) Firmware Reset fertig. ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetComplete {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gab einen Fehler beim Board Reset. Aktiviere Logging für mehr Informationen..
        /// </summary>
        internal static string uiMessageFirmwareResetError {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update von {0} an {1} (Modul {2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetStatus {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Reset Deines Boards war erfolgreich..
        /// </summary>
        internal static string uiMessageFirmwareResetSuccessful {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) Firmware Reset time out. ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Reset.
        /// </summary>
        internal static string uiMessageFirmwareResetTitle {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) Firmware Update fertig.({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateComplete {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update von {0} an {1} (Modul {2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateStatus {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) Firmware Update time out ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein oder mehrer Boards konnten nicht automatisch mit der MobiFlight Firmware geflasht werden.
        ///
        ///{0}
        ///
        ///Bitte führe im nächsten Dialog das Flashen manuell durch und wähle den passenden Board-Typ aus dem Kontextmenü..
        /// </summary>
        internal static string uiMessageFirmwareUploadAmbiguousBoards {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadAmbiguousBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gab einen Fehler beim Firmware Upload. Aktiviere Logging für mehr Informationen..
        /// </summary>
        internal static string uiMessageFirmwareUploadError {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Firmware Update war erfolgreich!.
        /// </summary>
        internal static string uiMessageFirmwareUploadSuccessful {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Firmware Upload hat einen Timeout gemeldet. Aktiviere Logging für mehr Informationen..
        /// </summary>
        internal static string uiMessageFirmwareUploadTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        internal static string uiMessageFirmwareUploadTitle {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Flugsimulator wurde beendet. Die Ausführung der Konfiguration wurde gestoppt. Starten Sie den Flugsimulator neu um die Konfiguration erneut auszuführen..
        /// </summary>
        internal static string uiMessageFsHasBeenStopped {
            get {
                return ResourceManager.GetString("uiMessageFsHasBeenStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Multiply-Feld muss eine gültige Zahl enthalten..
        /// </summary>
        internal static string uiMessageFsuipcConfigPanelMultiplyWrongFormat {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConfigPanelMultiplyWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert darf nicht leer sein. Verwende Zahlen oder Expression wie $+1, etc..
        /// </summary>
        internal static string uiMessageFsuipcConfigPanelNoValue {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConfigPanelNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zu FSUIPC wurde unterbrochen..
        /// </summary>
        internal static string uiMessageFsuipcConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte Prüfe den Pfad zur Arduino IDE. Das Tool avrdude konnte nicht gefunden werden..
        /// </summary>
        internal static string uiMessageInvalidArduinoIdePath {
            get {
                return ResourceManager.GetString("uiMessageInvalidArduinoIdePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe! Bitte nur hexadezimale Zahlen angeben..
        /// </summary>
        internal static string uiMessageInvalidValueHexOnly {
            get {
                return ResourceManager.GetString("uiMessageInvalidValueHexOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst kein weiteres {0} hinzufügen. Die maximale Anzahl sind {1} bei einem {2}..
        /// </summary>
        internal static string uiMessageMaxNumberOfDevicesReached {
            get {
                return ResourceManager.GetString("uiMessageMaxNumberOfDevicesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFConnector noch aktiv.
        /// </summary>
        internal static string uiMessageMFConnectorInterfaceActive {
            get {
                return ResourceManager.GetString("uiMessageMFConnectorInterfaceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altes Format erkannt (&lt;6.0). Die Konfiguration muss konvertiert werden. Möchtest Du sie unter einem neuen Namen speichern?.
        /// </summary>
        internal static string uiMessageMigrateConfigFileV60YesNo {
            get {
                return ResourceManager.GetString("uiMessageMigrateConfigFileV60YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Konfiguration muss konvertiert und unter neuem Namen gespeichert werden..
        /// </summary>
        internal static string uiMessageMigrateConfigFileYesNo {
            get {
                return ResourceManager.GetString("uiMessageMigrateConfigFileYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefundene Module anzeigen.
        /// </summary>
        internal static string uiMessageModuleFound {
            get {
                return ResourceManager.GetString("uiMessageModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angeschlossenen Arcaze Module sind scheinbar noch nicht konfiguriert. Die ist ein neues Feature, um besser &quot;Extension-Module&quot; zu unterstützen.
        ///
        ///Führen Sie die Konfiguration jetzt unbedingt durch..
        /// </summary>
        internal static string uiMessageModulesNotConfiguredYet {
            get {
                return ResourceManager.GetString("uiMessageModulesNotConfiguredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Update verfügbar!.
        /// </summary>
        internal static string uiMessageNewUpdateAvailable {
            get {
                return ResourceManager.GetString("uiMessageNewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAH! - Neue Version {0} verfügbar. Bitte jetzt aktualisieren..
        /// </summary>
        internal static string uiMessageNewUpdateAvailablePleaseUpdate {
            get {
                return ResourceManager.GetString("uiMessageNewUpdateAvailablePleaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine aktive FSUIPC Verbindung..
        /// </summary>
        internal static string uiMessageNoFSUIPCConnection {
            get {
                return ResourceManager.GetString("uiMessageNoFSUIPCConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Module gefunden.
        /// </summary>
        internal static string uiMessageNoModuleFound {
            get {
                return ResourceManager.GetString("uiMessageNoModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst schon alle Configs referenzieren. Mehr hinzuzufügen macht keinen Sinn..
        /// </summary>
        internal static string uiMessageNoMoreConfigReferenceAvailable {
            get {
                return ResourceManager.GetString("uiMessageNoMoreConfigReferenceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine fehlenden Joysticks gefunden..
        /// </summary>
        internal static string uiMessageNoNotConnectedJoysticksInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNoNotConnectedJoysticksInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind keine verwaisten Serial-Einträge in der aktuellen Konfiguration enthalten..
        /// </summary>
        internal static string uiMessageNoOrphanedSerialsFound {
            get {
                return ResourceManager.GetString("uiMessageNoOrphanedSerialsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine aktive SimConnect Verbindung..
        /// </summary>
        internal static string uiMessageNoSimConnectConnection {
            get {
                return ResourceManager.GetString("uiMessageNoSimConnectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Joysticks sind aktuell nicht angeschlossen, werden aber in der Config verwendet:
        ///
        ///{0}
        ///
        ///Die entsprechenden Konfigurationen funktionieren nicht bis der Joystick wieder angeschlossen und MobiFlight neu gestartet ist..
        /// </summary>
        internal static string uiMessageNotConnectedJoysticksInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNotConnectedJoysticksInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht genügend Pins.
        /// </summary>
        internal static string uiMessageNotEnoughPinsHint {
            get {
                return ResourceManager.GetString("uiMessageNotEnoughPinsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht genügend freie Pins zum Anlegen dieses Devices vorhanden.
        /// </summary>
        internal static string uiMessageNotEnoughPinsMessage {
            get {
                return ResourceManager.GetString("uiMessageNotEnoughPinsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch nicht implementiert..
        /// </summary>
        internal static string uiMessageNotImplementedYet {
            get {
                return ResourceManager.GetString("uiMessageNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast die aktuellste Version {0}. Kein Update notwendig..
        /// </summary>
        internal static string uiMessageNoUpdateNecessary {
            get {
                return ResourceManager.GetString("uiMessageNoUpdateNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss eine Zahl sein und größer als 0..
        /// </summary>
        internal static string uiMessagePanelsStepperInputRevolutionsMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("uiMessagePanelsStepperInputRevolutionsMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert darf nicht leer sein..
        /// </summary>
        internal static string uiMessagePanelsStepperInputRevolutionsMustNonEmpty {
            get {
                return ResourceManager.GetString("uiMessagePanelsStepperInputRevolutionsMustNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbedingung ist nicht erfüllt..
        /// </summary>
        internal static string uiMessagePreconditionNotSatisfied {
            get {
                return ResourceManager.GetString("uiMessagePreconditionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Config konnte nicht geladen werden. Bitte prüfe auf Syntaxfehler..
        /// </summary>
        internal static string uiMessageProblemLoadingConfig {
            get {
                return ResourceManager.GetString("uiMessageProblemLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit diese Änderung wirksam wird, benötigt MobiFlight einen Neustart..
        /// </summary>
        internal static string uiMessageRestartRequired {
            get {
                return ResourceManager.GetString("uiMessageRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ausgewählte Modul enthält keine Eingabegeräte. Möchtest Du welche konfigurieren?.
        /// </summary>
        internal static string uiMessageSelectedModuleDoesNotContainAnyInputDevices {
            get {
                return ResourceManager.GetString("uiMessageSelectedModuleDoesNotContainAnyInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ausgewählte Modul enthält keine Ausgabegeräte. Möchtest Du welche konfigurieren?.
        /// </summary>
        internal static string uiMessageSelectedModuleDoesNotContainAnyOutputDevices {
            get {
                return ResourceManager.GetString("uiMessageSelectedModuleDoesNotContainAnyOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Firmware auf diesem Board unterstützt die Funktion noch nicht. Update auf die aktuellste Firmware zuerst!.
        /// </summary>
        internal static string uiMessageSettingsDialogFirmwareVersionTooLowException {
            get {
                return ResourceManager.GetString("uiMessageSettingsDialogFirmwareVersionTooLowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alte firmware, update jetzt!.
        /// </summary>
        internal static string uiMessageSettingsDlgOldFirmware {
            get {
                return ResourceManager.GetString("uiMessageSettingsDlgOldFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zu SimConnect wurde unterbrochen..
        /// </summary>
        internal static string uiMessageSimConnectConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageSimConnectConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Treffer gefunden.
        /// </summary>
        internal static string uiMessagesSimConnectPanelMatchesFound {
            get {
                return ResourceManager.GetString("uiMessagesSimConnectPanelMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Alle zeigen - .
        /// </summary>
        internal static string uiMessagesSimConnectPanelShowAll {
            get {
                return ResourceManager.GetString("uiMessagesSimConnectPanelShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler im Test-Modus: Modul nicht angeschlossen..
        /// </summary>
        internal static string uiMessageTestModeModuleNotConnected {
            get {
                return ResourceManager.GetString("uiMessageTestModeModuleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei Transform. .
        /// </summary>
        internal static string uiMessageTransformError {
            get {
                return ResourceManager.GetString("uiMessageTransformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest Du das automatische Updaten von neuen Arduinos deaktivieren?
        ///Du kannst es jederzeit wieder in den Einstellungen aktivieren .
        /// </summary>
        internal static string uiMessageUpdateArduinoFwAutoDisableYesNo {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoFwAutoDisableYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden kompatible Arduinos ohne MobiFlight Firmware gefunden. Um sie zu verwenden benötigen sie die neueste Firmware.
        ///
        ///Jetzt MobiFlight Firmware hochladen!.
        /// </summary>
        internal static string uiMessageUpdateArduinoOkCancel {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoOkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompatible Boards gefunden!.
        /// </summary>
        internal static string uiMessageUpdateArduinoTitle {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Firmware der MobiFlight Boards ist nicht aktuell - jetzt updaten?.
        /// </summary>
        internal static string uiMessageUpdateOldFirmwareOkCancel {
            get {
                return ResourceManager.GetString("uiMessageUpdateOldFirmwareOkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Firmware verfügbar!.
        /// </summary>
        internal static string uiMessageUpdateOldFirmwareTitle {
            get {
                return ResourceManager.GetString("uiMessageUpdateOldFirmwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest Du Dein Board wirklich mit der Config aktualisieren?.
        /// </summary>
        internal static string uiMessageUploadConfigurationConfirm {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Upload ist fertig!.
        /// </summary>
        internal static string uiMessageUploadConfigurationFinished {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Upload war nicht erfolgreich..
        /// </summary>
        internal static string uiMessageUploadConfigurationFinishedWithError {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Upload.
        /// </summary>
        internal static string uiMessageUploadConfigurationHint {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Config ist zu lang, mach ein paar Geräte-Namen kürzer..
        /// </summary>
        internal static string uiMessageUploadConfigurationTooLong {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert muss eine Zahl zwischen {0} und {1} sein..
        /// </summary>
        internal static string uiMessageValidNumberInRange {
            get {
                return ResourceManager.GetString("uiMessageValidNumberInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neueste WASM Events konnten nicht installiert werden. Bitte checke das Log für weitere Details..
        /// </summary>
        internal static string uiMessageWasmEventsInstallationError {
            get {
                return ResourceManager.GetString("uiMessageWasmEventsInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neueste WASM Events wurden erfolgreich installiert..
        /// </summary>
        internal static string uiMessageWasmEventsInstallationSuccessful {
            get {
                return ResourceManager.GetString("uiMessageWasmEventsInstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast das aktuelle MobiFlight WASM Modul bereits installiert..
        /// </summary>
        internal static string uiMessageWasmUpdateAlreadyInstalled {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSFS2020 Community Verzeichnis nicht gefunden. WASM Module kann nicht automatisch kopiert werden. Bitte kopiere das Verzeichnis manuell an die richtige Stelle..
        /// </summary>
        internal static string uiMessageWasmUpdateCommunityFolderNotFound {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateCommunityFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module konnte nicht installiert werden. Bitte checke das Log für weitere Details..
        /// </summary>
        internal static string uiMessageWasmUpdateInstallationError {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module Installation.
        /// </summary>
        internal static string uiMessageWasmUpdater {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Änderung benötigt einen Neustart von MobiFlight..
        /// </summary>
        internal static string uiSettingsMobiFlightChangeRequiresRestart {
            get {
                return ResourceManager.GetString("uiSettingsMobiFlightChangeRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mobiflight.com/de/dokumentation/software.html.
        /// </summary>
        internal static string WebsiteUrlHelp {
            get {
                return ResourceManager.GetString("WebsiteUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPUIPC Status.
        /// </summary>
        internal static string xpuipcStatus {
            get {
                return ResourceManager.GetString("xpuipcStatus", resourceCulture);
            }
        }
    }
}
